### ISSUE TITLE
Замечания к проекту

### ISSUE THREAD

**Issue by FreddyMcRay** [Anron97/MyPock#1]
В общем идея проекта интересная, и такое приложение будет полезно почти всем пользователям сети интернет. Но в описании есть несколько "шероховатостей".

1. Присутствуют опечатки

- В мокапе "MainPage.png" написано "Nane resource" вместо (на мой взгляд правильного) "Resource name".

- В файле "MyPock.txt" в 3 строке слово "сохранять" дублируется.

2. Не понятно, как именно можно добавить ресурс в избранное.

**Comment by Anron97** [comment]
Исправлено
